/**
 * Layout raiz do aplicativo Study Flow.
 * Define a estrutura HTML base, fontes padrão (Geist e Geist Mono) e importações de estilos globais.
 * @packageDocumentation
 */

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

/**
 * Configuração da fonte Geist Sans.
 */
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

/**
 * Configuração da fonte Geist Mono.
 */
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/**
 * Metadados globais da aplicação.
 * Utilizado pelo Next.js para renderizar tags HTML de SEO e cabeçalhos da página.
 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Componente de Layout Raiz (Root Layout).
 * Serve como o wrapper principal para todas as páginas da aplicação.
 *
 * @param props - Propriedades do componente.
 * @param props.children - Elementos filhos (páginas ou outros sublayouts) a serem renderizados dentro do body.
 * @returns Um elemento HTML contendo a estrutura base (`<html>` e `<body>`) com estilos globais aplicados.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}

